import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export const getServerSideProps = async () => {
  const cliente = new ApolloClient({
    uri: "http://localhost:5000/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await cliente.query({
    query: gql`
      query MyQuery {
        personas {
          nodes {
            id
            nombre
            apellido
          }
        }
      }
    `,
  });

  // console.log(data.personas.nodes);
  // console.log(data.personas.nodes[1] + " estos son los datos hasta nodes");

  return {
    props: {
      launches: data.personas.nodes,
    },
  };
};

export default function Launches({ launches }) {
  console.log(launches);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>porque esto no sirve</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {launches.map((launch) => (
            <a
              key={launch.id}
              href="https://nextjs.org/docs"
              className={styles.card}
            >
              <h2>
                {launch.nombre} {launch.apellido} &rarr;
              </h2>
              <p> dsdsadasdasdasdasdasdasdasdasdasd</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

// export async function getStaticProps(){
//   const client = new Apolloclient({
//   uri:
//   })
// }
